name: ProjectR
version: ${project.version}
main: collinvht.projectr.ProjectR
api-version: 1.18
depend: [ MTVehicles, WorldEdit, LuckPerms, JDA ]
authors: [ Collinvht ]
commands:
  race:
    description: Starts races
  blockslowdown:
    permission: projectr.fia.common
    description: Blockslowdown
  timetrial:
    permission: projectr.fia.common
    description: Starts timetrial