name: ProjectR
version: ${project.version}
main: collinvht.projectr.ProjectR
api-version: 1.16
depend: [ MTVehicles, WorldEdit, LuckPerms, JDA ]
authors: [ Collinvht ]
commands:
  race:
    permission: projectr.fia.race
    description: Starts races