name: ZenticRacing
version: ${project.version}
main: collinvht.zenticracing.ZenticRacing
api-version: 1.16
depend: [ VehiclesPlusPro, WorldEdit, LuckPerms, JDA ]
authors: [ Collinvht ]
commands:
  warning:
    aliases: warn
    description: Warn people
    permission: zentic.fia
  race:
    permission: zentic.fia
    description: Starts races
  persoonlijkrecord:
    description: Persoonlijk Record
  snelste:
    description: Snelste tijden
  stand:
    description: Stand
  penalty:
    aliases: penalty
    description: Give people a penalty
    permission: zentic.fia
  dsq:
    aliases: dsq
    description: Give people a dsq
    permission: zentic.fia
  flag:
    aliases: vlag
    description: Bring out a flag
    permission: zentic.fia
  lights:
    aliases: lichten
    description: Start de lichten
    permission: zentic.fia
  garage:
    aliases: spawnkart, spawncar
    description: Spawn a kart
    permission: zentic.fia
  clearchat:
    description: ClearChat
    permission: zentic.fia
  muteutil:
    description: MuteUtil
  teambaan:
    description: Teambaan
  raceteam:
    description: Team
  golfkar:
    description: Spawn golfkar
    permission: zentic.spawngolf
