name: F1MC
version: ${project.version}
main: collinvht.f1mc.F1MC
api-version: 1.19
depend:
  - VehiclesPlusPro
  - NametagEdit
  - WorldEdit
  - LuckPerms
  - JDA
  - ItemsAdder
  - ProtocolLib
authors:
  - Collinvht
  - SBDeveloper

commands:
  raceteam:
    description: Manage or create teams
  race:
    description: Start or manage races
  slowdown:
    permission: projectr.fia.common
    description: Blockslowdown
  timetrial:
    permission: projectr.fia.common
    description: Starts timetrial
  dsq:
    permission: projectr.fia.common
    description: Disqualifies someone
  flag:
    permission: projectr.fia.common
    description: Sets a flag or edits the locations
  warning:
    permission: projectr.fia.common
    description: Gives a warning
  penalty:
    permission: projectr.fia.common
    description: Gives a penalty
  announcement:
    permission: projectr.fia.common
    description: Announce something
  tyre:
    permission: projectr.fia.admin
    description: Tyre
  country:
    description: Sets your country