name: F1MC
version: ${project.version}
main: collinvht.f1mc.F1MC
api-version: 1.19
depend:
  - VehiclesPlusPro
  - NametagEdit
  - WorldEdit
  - LuckPerms
  - JDA
  - ItemsAdder
  - ProtocolLib
  - Multiverse-Core
  - HeadDB
  - DecentHolograms
authors:
  - Collinvht
  - SBDeveloper

commands:
  helpfia:
    description: Help FIA
  discord:
    description: Discord link
  raceteam:
    description: Manage or create teams
  race:
    description: Start or manage races
  slowdown:
    permission: f1mc.fia.common
    description: Blockslowdown
  timetrial:
    aliases: tt
    description: Timetrial
    permission: f1mc.timetrial
  dsq:
    permission: f1mc.fia.common
    description: Disqualifies someone
  flag:
    permission: f1mc.fia.common
    description: Sets a flag or edits the locations
  warning:
    permission: f1mc.fia.common
    description: Gives a warning
  penalty:
    permission: f1mc.fia.common
    description: Gives a penalty
  announcement:
    permission: f1mc.fia.common
    description: Announce something
  tyre:
    permission: f1mc.fia.admin
    description: Tyre
  creplace:
    permission: f1mc.builder
    description: Custom replace
  cset:
    permission: f1mc.builder
    description: Custom Set
  creplacenear:
    permission: f1mc.builder
    description: Custom Replacenear
  cundo:
    permission: f1mc.builder
    description: Custom Undo
  country:
    description: Sets your country
  forecast:
    description: Predicts the upcomming weather
  weather:
    description: Sets the weather
    permission: f1mc.fia.common