name: ProjectR
version: ${project.version}
main: collinvht.projectr.ProjectR
api-version: 1.18
depend: [ MTVehicles, WorldEdit, LuckPerms, JDA, ItemsAdder  ]
authors: [ Collinvht, SBDeveloper ]
commands:
  raceteam:
    description: Manage or create teams
  race:
    description: Start or manage races
  slowdown:
    permission: projectr.fia.common
    description: Blockslowdown
  timetrial:
    permission: projectr.fia.common
    description: Starts timetrial